PUT https://localhost:8443/user/flag
Content-Type: application/json

{
    "username": "User120"
}

### Delete User - success
DELETE https://localhost:8443/profile/User120
Content-Type: application/json