### Register a new user
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "user1",
    "password": "pwd2aaaaaaa",
    "authorities": "ROLE_USER"
}

### Register a user with a duplicated username
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "user1",
    "password": "pwd2aaaaaaa",
    "authorities": "ROLE_USER"
}

### Register a user with password too short
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "user",
    "password": "pwdsalfdkjsdf1",
    "authorities": "ROLE_USER"
}

### Retrieve all users
GET http://localhost:8080/users

### Update match
PUT http://localhost:8080/match/updateList
Content-Type: application/json

[
    {
        "id": 1,
        "round": null,
        "white": "white1",
        "black": "black1",
        "BYE": false,
        "result": 1.0
    },
    {
        "id": 2,
        "round": null,
        "white": "white2",
        "black": "black2",
        "BYE": true,
        "result": -1.0
    }
]

