### Register a new user
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "user1",
    "password": "pwd2aaaaaaa",
    "authorities": "ROLE_USER"
}

### Register a user with a duplicated username
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "user1",
    "password": "pwd2aaaaaaa",
    "authorities": "ROLE_USER"
}

### Register a user with password too short
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "user",
    "password": "pwdsalfdkjsdf1",
    "authorities": "ROLE_USER"
}

### Retrieve all users
GET http://localhost:8080/users

### Retrieve Tournament Data for User
GET http://localhost:8080/tournaments
Content-Type: application/json
Authorization: Basic VXNlcjp1c2VyMTIzNA==